theme = "autumn"
# theme = "tokyonight_storm"

[editor]
line-number = "relative"
auto-format = false
color-modes = true
auto-save = true
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
